### ISSUE TITLE
Invalid video timecode for the collection chest

### ISSUE THREAD

**Issue by igor725** [Malin001/Legilimens-Hogwarts-Legacy-cpp#3]
The video time code for `The Highlands - Manor Cape Collection Chest #7` points to the `Collection Chest #6`. It must be https://youtu.be/gYs24rpRPZ0?t=722, not https://youtu.be/gYs24rpRPZ0&t=418.

**Comment by Malin001** [comment]
Good catch! The timestamp should be fixed as of v0.2.4
